[toolchain]
channel = "stable"
components = [ "rustfmt", "rustc" ]
targets = [ "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "aarch64-unknown-linux-gnu", "aarch64-unknown-linux-musl" ]
profile = "minimal"
